- name: install nginx
  hosts: frontend
  become: yes #provide root access for ansible 
  tasks:
  - name: install nginx
    ansible.builtin.package:
    name: nginx
    stage: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx  
      state: started
      enabled: yes