- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}" #item is reserved if written or not
    loop:
    - Bhaskar
    - sindhu
    - Rama
    - satyaveni  